spring:
  application:
    name: articles
  datasource:
    url: jdbc:postgresql://localhost:5432/article-db
    username: postgres
    password: "1234"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9090
jwt:
  secret-key: INSolution
  token-validity: 86400000
